<?php
namespace WaflCones\DataModel;

use \DblEj\Data\Field;

/**
 * Sale
 * Represents a row in the database table Sales
 */
abstract class Sale
extends \DblEj\Data\PersistableModel
{

    /**
     * SaleId
     *
     * Data Storage (DblEj\Data\StorageEngines\Mysql): 
     *        Primary Key
     *        Type: DATA_TYPE_INT unsigned
     *        Default: null
     *
     * @var integer
     */
    protected $_saleId;

    /**
     * SaleDate
     *
     * Data Storage (DblEj\Data\StorageEngines\Mysql): 
     *        Type: DATA_TYPE_INT unsigned
     *        Default: null
     *
     * @var integer
     */
    protected $_saleDate;

    /**
     * Price
     *
     * Data Storage (DblEj\Data\StorageEngines\Mysql): 
     *        Type: DATA_TYPE_DECIMAL
     *        Default: null
     *
     * @var float
     */
    protected $_price;

    /**
     * EmployeeId
     *
     * Data Storage (DblEj\Data\StorageEngines\Mysql): 
     *        Type: DATA_TYPE_INT unsigned
     *        Default: null
     *
     * @var integer
     */
    protected $_employeeId;
    /**
     * Get_FieldDataTypes
     *
     * Get an array of this model's fields and their data types
     *
     */
    public static function GetFieldDataTypes()
    {
        $fieldTypes = array();
                $fieldTypes["SaleId"] = Field::DATA_TYPE_INT;
        $fieldTypes["SaleDate"] = Field::DATA_TYPE_INT;
        $fieldTypes["Price"] = Field::DATA_TYPE_DECIMAL;
        $fieldTypes["EmployeeId"] = Field::DATA_TYPE_INT;
        return $fieldTypes;
    }

    /**
     * Search
     *
     * Search an index for the given criteria and return matching Sales.
     * An "index" in this context refers to an implementor of IIndex and is generated by an IIndexer (such as the Apache Solr Indexer Extension).
     *
     * @param string $searchFieldName The name of the INDEX FIELD (not necessarily the same as the model or table's field) to search on.
     * @param string $searchValue The indexed value to search for.
     * @param \DblEj\Data\IndexSort[] $sorts How to sort the results.
     * @param \DblEj\Data\IIndex $searchIndex Which index to seach.  If not provided, the default search index will be used.
     * @return \WaflCones\FunctionalModel\Sale[]
     * @throws \Exception
     */
    public static function Search($searchFieldName, $searchValue, $sorts = null, \DblEj\Data\IIndex $searchIndex = null)
    {
        self::Initialize();
        return self::_search($searchFieldName, $searchValue, $sorts, $searchIndex);
    }

    /**
     * Filter
     *
     * Get the Sale's from the Storage Engine that matches the given filter and other criteria.
     *
     * @param string $filter optional The filter to filter by.  If no filter is passed in, then all results are returned.
     * @param string $orderByFieldName optional The name of the field to order the Sale's by
     * @param int $maxRecordCount optional The maximum number of Sale's to return
     * @param string $groupingField optional
     * @param array $joinObjects optional The tables and fields to join as part of the search criteria (note: joined columns are not returned as properties of the data model).
     * @param int $startOffset optional
     * @param string $arrayKeyField optional
     * @return \WaflCones\FunctionalModel\Sale[] an array of the matching Sales
     * @throws DataModelException
     * @throws DataException
     */
    public static function Filter($filter = null, $orderByFieldName = null, $maxRecordCount = null, $groupingField = null,
    $joinObjects = null, $startOffset = 0, $arrayKeyField = null)
    {
        self::Initialize();
        return self::_filter($filter, $orderByFieldName, $maxRecordCount, $groupingField, $joinObjects, $startOffset, $arrayKeyField);
    }

    /**
     * FilterFirst
     *
     * Get the Sale's from the Storage Engine that matches the given filter and other criteria.
     *
     * @param string $filter
     * @param string $orderByFieldName
     * @param string $groupingField
     * @param array $joinObjects
     * @return null|\WaflCones\FunctionalModel\Sale the first matching Sales
     * @throws DataModelException
     */
    public static function FilterFirst($filter = null, $orderByFieldName = null, $groupingField = null, $joinObjects = null)
    {
        self::Initialize();
        return self::_filterFirst($filter, $orderByFieldName, $groupingField, $joinObjects);
    }


    /**
     * Get the current SaleId for this Sale.
     *
     * @return integer The SaleId
     */
    public function Get_SaleId()
    {
        return $this->_saleId;
    }

    /**
     * Set the SaleId for this Sale
     *
     * @return \WaflCones\FunctionalModel\Sale This instance is returned back to the caller to facilitate chained method calls
     */
    public function Set_SaleId($saleId)
    {
        if ($this->_saleId !== $saleId)
        {
            $this->_saleId = $saleId;
            $this->ModelChanged("SaleId");
        }
        return $this;
    }


    /**
     * Get the current SaleDate for this Sale.
     *
     * @return integer The SaleDate
     */
    public function Get_SaleDate()
    {
        return $this->_saleDate;
    }

    /**
     * Set the SaleDate for this Sale
     *
     * @return \WaflCones\FunctionalModel\Sale This instance is returned back to the caller to facilitate chained method calls
     */
    public function Set_SaleDate($saleDate)
    {
        if ($this->_saleDate !== $saleDate)
        {
            $this->_saleDate = $saleDate;
            $this->ModelChanged("SaleDate");
        }
        return $this;
    }


    /**
     * Get the current Price for this Sale.
     *
     * @return float The Price
     */
    public function Get_Price()
    {
        return $this->_price;
    }

    /**
     * Set the Price for this Sale
     *
     * @return \WaflCones\FunctionalModel\Sale This instance is returned back to the caller to facilitate chained method calls
     */
    public function Set_Price($price)
    {
        if ($this->_price !== $price)
        {
            $this->_price = $price;
            $this->ModelChanged("Price");
        }
        return $this;
    }


    /**
     * Get the current EmployeeId for this Sale.
     *
     * @return integer The EmployeeId
     */
    public function Get_EmployeeId()
    {
        return $this->_employeeId;
    }

    /**
     * Set the EmployeeId for this Sale
     *
     * @return \WaflCones\FunctionalModel\Sale This instance is returned back to the caller to facilitate chained method calls
     */
    public function Set_EmployeeId($employeeId)
    {
        if ($this->_employeeId !== $employeeId)
        {
            $this->_employeeId = $employeeId;
            $this->ModelChanged("EmployeeId");
        }
        return $this;
    }

    public static function GetBySaleItems($flavorId = null, $sortBy = null)
    {
        $subclass = get_called_class();
        return $subclass::Select
        (
            ($flavorId?"SaleItems.FlavorId = '$flavorId'":"1=1"),
            $sortBy,
            null,
            null,
            array
            (
                "SaleItems"=>"SaleId"
            )
        );
    }

    /**
    * Get the related Employee
    *
    * @return \WaflCones\FunctionalModel\Employee The Employee
    */
    public function GetEmployee($sortBy = null)
    {
        return \WaflCones\FunctionalModel\Employee::SelectFirst("EmployeeId = '".$this->Get_EmployeeId()."'", $sortBy);
    }

    /**
     * Get Flavors related to this Sale (cross-ref: SaleItems)
     *
     * @return \WaflCones\FunctionalModel\Flavor[]
     */
    public function GetFlavorsCrossReferencedBySaleItems($sortBy = null)
    {
        return \WaflCones\FunctionalModel\Flavor::Select("SaleItems.SaleId = '".$this->Get_SaleId()."'", $sortBy, null, null, array("SaleItems"=>"FlavorId"));
    }

    /**
     * Get the SaleItems for this Sale
     *
     * @param $sortBy The name of the field to sort on
     * @return \WaflCones\FunctionalModel\SaleItem[]
     */
    public function GetSaleItems($flavorId = null, $sortBy = null)
    {
        if ($this->Get_SaleId())
        {
            $clause = "SaleId = '".$this->Get_SaleId()."'";
            if ($flavorId)
            {
                $clause .= "and FlavorId = '$flavorId'";
            }

            return \WaflCones\FunctionalModel\SaleItem::Select($clause, $sortBy);
        } else {
            return array();
        }
    }

    /**
    * Gets the name of the field that stores a unique key identifying each instance.
    * This is often the primary key in your database table.
    *
    * @return string
    */
    public static function Get_KeyFieldName()
    {
        return "SaleId";
    }

    /**
    * Whether or not the values in the KeyField are generated automatically (like a database auto-increment) or if they generated manually.
    *
    * @return boolean TRUE if the values are generated automatically by the engine, otherwise FALSE
    */
    public static function Get_KeyIsAutoGenerated()
    {
        return true;
    }

    /**
    * A Storage Engine specific string that tells the Storage Engine where this Model is to be stored.
    * This is typically the name of a database table.
    *
    * @return string
    */
    public static function Get_Destination()
    {
        return "Sales";
    }

    /**
    * An arbitrary logical grouping for objects that can be stored in a storage engine.
    * If you have a Storage Engine set up with the same Storage Group, then ActiveWafl will use that storage engine when retrieving and persisting models of this type.
    * @return string
    */
    public static function Get_StorageGroup()
    {
        return "WaflCones";
    }
}