<?php
namespace WaflCones\DataModel;

use \DblEj\Data\Field;

/**
 * Session
 * Represents a row in the database table Sessions
 */
abstract class Session
extends \Wafl\Extensions\UserAuth\FunctionalModel\PersistantSession
{

    /**
     * SessionId
     *
     * Data Storage (DblEj\Data\StorageEngines\Mysql): 
     *        Primary Key
     *        Type: DATA_TYPE_STRING
     *        Default: null
     *
     * @var string
     */
    protected $_sessionId;

    /**
     * EmployeeId
     *
     * Data Storage (DblEj\Data\StorageEngines\Mysql): 
     *        Type: DATA_TYPE_INT unsigned
     *        Default: null
     *
     * @var integer
     */
    protected $_employeeId;
    /**
     * Get_FieldDataTypes
     *
     * Get an array of this model's fields and their data types
     *
     */
    public static function GetFieldDataTypes()
    {
        $fieldTypes = array();
                $fieldTypes["SessionId"] = Field::DATA_TYPE_STRING;
        $fieldTypes["EmployeeId"] = Field::DATA_TYPE_INT;
        return $fieldTypes;
    }

    /**
     * Search
     *
     * Search an index for the given criteria and return matching Sessions.
     * An "index" in this context refers to an implementor of IIndex and is generated by an IIndexer (such as the Apache Solr Indexer Extension).
     *
     * @param string $searchFieldName The name of the INDEX FIELD (not necessarily the same as the model or table's field) to search on.
     * @param string $searchValue The indexed value to search for.
     * @param \DblEj\Data\IndexSort[] $sorts How to sort the results.
     * @param \DblEj\Data\IIndex $searchIndex Which index to seach.  If not provided, the default search index will be used.
     * @return \WaflCones\FunctionalModel\Session[]
     * @throws \Exception
     */
    public static function Search($searchFieldName, $searchValue, $sorts = null, \DblEj\Data\IIndex $searchIndex = null)
    {
        self::Initialize();
        return self::_search($searchFieldName, $searchValue, $sorts, $searchIndex);
    }

    /**
     * Filter
     *
     * Get the Session's from the Storage Engine that matches the given filter and other criteria.
     *
     * @param string $filter optional The filter to filter by.  If no filter is passed in, then all results are returned.
     * @param string $orderByFieldName optional The name of the field to order the Session's by
     * @param int $maxRecordCount optional The maximum number of Session's to return
     * @param string $groupingField optional
     * @param array $joinObjects optional The tables and fields to join as part of the search criteria (note: joined columns are not returned as properties of the data model).
     * @param int $startOffset optional
     * @param string $arrayKeyField optional
     * @return \WaflCones\FunctionalModel\Session[] an array of the matching Sessions
     * @throws DataModelException
     * @throws DataException
     */
    public static function Filter($filter = null, $orderByFieldName = null, $maxRecordCount = null, $groupingField = null,
    $joinObjects = null, $startOffset = 0, $arrayKeyField = null)
    {
        self::Initialize();
        return self::_filter($filter, $orderByFieldName, $maxRecordCount, $groupingField, $joinObjects, $startOffset, $arrayKeyField);
    }

    /**
     * FilterFirst
     *
     * Get the Session's from the Storage Engine that matches the given filter and other criteria.
     *
     * @param string $filter
     * @param string $orderByFieldName
     * @param string $groupingField
     * @param array $joinObjects
     * @return null|\WaflCones\FunctionalModel\Session the first matching Sessions
     * @throws DataModelException
     */
    public static function FilterFirst($filter = null, $orderByFieldName = null, $groupingField = null, $joinObjects = null)
    {
        self::Initialize();
        return self::_filterFirst($filter, $orderByFieldName, $groupingField, $joinObjects);
    }


    /**
     * Get the current SessionId for this Session.
     *
     * @return string The SessionId
     */
    public function Get_SessionId()
    {
        return $this->_sessionId;
    }

    /**
     * Set the SessionId for this Session
     *
     * @return \WaflCones\FunctionalModel\Session This instance is returned back to the caller to facilitate chained method calls
     */
    public function Set_SessionId($sessionId)
    {
        if ($this->_sessionId !== $sessionId)
        {
            $this->_sessionId = $sessionId;
            $this->ModelChanged("SessionId");
        }
        return $this;
    }


    /**
     * Get the current EmployeeId for this Session.
     *
     * @return integer The EmployeeId
     */
    public function Get_EmployeeId()
    {
        return $this->_employeeId;
    }

    /**
     * Set the EmployeeId for this Session
     *
     * @return \WaflCones\FunctionalModel\Session This instance is returned back to the caller to facilitate chained method calls
     */
    public function Set_EmployeeId($employeeId)
    {
        if ($this->_employeeId !== $employeeId)
        {
            $this->_employeeId = $employeeId;
            $this->ModelChanged("EmployeeId");
        }
        return $this;
    }

    /**
    * Gets the name of the field that stores a unique key identifying each instance.
    * This is often the primary key in your database table.
    *
    * @return string
    */
    public static function Get_KeyFieldName()
    {
        return "SessionId";
    }

    /**
    * Whether or not the values in the KeyField are generated automatically (like a database auto-increment) or if they generated manually.
    *
    * @return boolean TRUE if the values are generated automatically by the engine, otherwise FALSE
    */
    public static function Get_KeyIsAutoGenerated()
    {
        return false;
    }

    /**
    * A Storage Engine specific string that tells the Storage Engine where this Model is to be stored.
    * This is typically the name of a database table.
    *
    * @return string
    */
    public static function Get_Destination()
    {
        return "Sessions";
    }

    /**
    * An arbitrary logical grouping for objects that can be stored in a storage engine.
    * If you have a Storage Engine set up with the same Storage Group, then ActiveWafl will use that storage engine when retrieving and persisting models of this type.
    * @return string
    */
    public static function Get_StorageGroup()
    {
        return "WaflCones";
    }
}